@startmindmap

* 自我修行
    * 专一
    * 排除
        * 情
            * 色情
            * 懒惰、懈怠
        * 环境
            * 卫生
            * 周边物品
        * 游戏
        * 视频
            * 电视剧
            * 电影

@endmindmap